<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="SingaravelanNandakumars-MacBook-Pro.local" name="4.0Appcases" tests="7" failures="3" timestamp="12 Feb 2018 11:43:10 GMT" time="27.534" errors="0">
  <testcase name="orderItemWithSavedCard" time="2.021" classname="co.bytemark.test.orders.OrdersRegressionCases"/>
  <testcase name="orderItemWithSavedCard" time="3.313" classname="co.bytemark.test.orders.OrdersRegressionCases"/>
  <testcase name="orderItemWithSavedCard" time="3.112" classname="co.bytemark.test.orders.OrdersRegressionCases"/>
  <testcase name="orderItemWithAdhocCard" time="2.202" classname="co.bytemark.test.orders.OrdersRegressionCases">
    <failure type="java.lang.AssertionError" message="expected [1] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [null]
	at co.bytemark.helper.Then.assertEquals(Then.java:48)
	at co.bytemark.test.orders.OrdersRegressionCases.orderItemWithAdhocCard(OrdersRegressionCases.java:91)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- orderItemWithAdhocCard -->
  <testcase name="orderItemWithAdhocCard" time="3.041" classname="co.bytemark.test.orders.OrdersRegressionCases">
    <failure type="java.lang.AssertionError" message="expected [3] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [null]
	at co.bytemark.helper.Then.assertEquals(Then.java:48)
	at co.bytemark.test.orders.OrdersRegressionCases.orderItemWithAdhocCard(OrdersRegressionCases.java:95)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- orderItemWithAdhocCard -->
  <testcase name="orderItemWithAdhocCard" time="3.117" classname="co.bytemark.test.orders.OrdersRegressionCases">
    <failure type="java.lang.AssertionError" message="expected [There was an error processing this transaction: An error has occurred when making a request (1), and the card has not been charged.] but found [The CVV was not found and is required for this merchant. Please provide one and try again.]">
      <![CDATA[java.lang.AssertionError: expected [There was an error processing this transaction: An error has occurred when making a request (1), and the card has not been charged.] but found [The CVV was not found and is required for this merchant. Please provide one and try again.]
	at co.bytemark.helper.Then.assertEquals(Then.java:48)
	at co.bytemark.test.orders.OrdersRegressionCases.orderItemWithAdhocCard(OrdersRegressionCases.java:99)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- orderItemWithAdhocCard -->
  <testcase name="orderWithAutoActivationPass" time="10.685" classname="co.bytemark.test.orders.OrdersRegressionCases"/>
</testsuite> <!-- 4.0Appcases -->
